server {
  listen 80;

  location /ohif/ {
    root /usr/share/nginx/html;
    rewrite ^/ohif/(.*)$ /$1 break;
    try_files $uri $uri/ /index.html;
  }

  location = /ohif {
    return 301 /ohif/;
  }

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html;
  }

  error_page   500 502 503 504  /50x.html;

  location = /50x.html {
    root   /usr/share/nginx/html;
  }
}
